package com.ruomm.appcorex.greendao.dbstore;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "DBENTRY_VALUE".
 */
@Entity
public class DBEntryValue {

    @Id(autoincrement = true)
    @Property(nameInDb = "id")
    private long id;

    @Property(nameInDb = "key")
    @NotNull
    private String key;

    @Property(nameInDb = "tag")
    private String tag;

    @Property(nameInDb = "value_tag")
    private String valueTag;

    @Property(nameInDb = "value")
    private String value;

    @Property(nameInDb = "update_time")
    private java.util.Date updateTime;

    @Generated
    public DBEntryValue() {
    }

    public DBEntryValue(long id) {
        this.id = id;
    }

    @Generated
    public DBEntryValue(long id, String key, String tag, String valueTag, String value, java.util.Date updateTime) {
        this.id = id;
        this.key = key;
        this.tag = tag;
        this.valueTag = valueTag;
        this.value = value;
        this.updateTime = updateTime;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @NotNull
    public String getKey() {
        return key;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setKey(@NotNull String key) {
        this.key = key;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getValueTag() {
        return valueTag;
    }

    public void setValueTag(String valueTag) {
        this.valueTag = valueTag;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public java.util.Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(java.util.Date updateTime) {
        this.updateTime = updateTime;
    }

}
